server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

cos:
   key: cos1234 
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/animal?serverTimezone=Asia/Seoul
    username: bobo
    password: bobo123
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  servlet:
    multipart:
      location: C:\upload
      maxFileSize: 300MB
      maxRequestSize: 200MB    
      
# 구글 로그인       
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 271421337386-4tcng428ubjktubhcpcfufpdfvu9asrk.apps.googleusercontent.com 
            client-secret: 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 
            scope:
              - email
              - profile
           
            
    
     

